sudo: false

language: go

go:
  - 1.16
  - 1.17
  - 1.18
  - tip

os:
  - linux

env:
  matrix:
    - CPU=8

script:
  - go test -v -cpu=$CPU -benchmem -bench=.

matrix:
  allow_failures:
    - go: tip
